AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Vanity number generator – Lambda + DynamoDB (On-Demand)

Globals:
  Function:
    Runtime: nodejs18.x
    Architectures: [arm64]
    MemorySize: 256      # 够用就行，可后调
    Timeout: 10
    Environment:
      Variables:
        TABLE_NAME: VanityNumbers

Resources:
  VanityTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VanityNumbers
      BillingMode: PAY_PER_REQUEST         # 即 On-Demand
      AttributeDefinitions:
        - AttributeName: callerNumber
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: callerNumber
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE

  VanityFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler.handler        # 注意：编译后路径
      CodeUri: .                           # SAM 自动取根目录
      Policies:
        - DynamoDBCrudPolicy:
            TableName: VanityNumbers

Outputs:
  VanityFunctionArn:
    Description: "ARN of the vanity Lambda"
    Value: !GetAtt VanityFunction.Arn
