AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Vanity number generator – Lambda + DynamoDB (On-Demand)

Globals:
  Function:
    Runtime: nodejs18.x
    MemorySize: 256
    Timeout: 10
    Environment:
      Variables:
        TABLE_NAME: VanityNumbers

Resources:
  VanityTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain    
    Properties:
      TableName: VanityNumbers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: callerNumber
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: callerNumber
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE

  VanityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: handler.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: VanityNumbers

Outputs:
  VanityFunctionArn:
    Description: ARN of the vanity Lambda
    Value: !GetAtt VanityFunction.Arn
